# Generated by Django 4.0.3 on 2022-03-16 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecognition',
            name='year',
            field=models.IntegerField(default=2015),
        ),
        migrations.AddField(
            model_name='internship',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academicrecognition',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_recognition', to='spapp.activities'),
        ),
        migrations.AlterField(
            model_name='communityservice',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_service', to='spapp.activities'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='faculty',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='internship',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='spapp.activities'),
        ),
        migrations.AlterField(
            model_name='project',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='spapp.activities'),
        ),
        migrations.AlterField(
            model_name='research',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='spapp.activities'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
