# Generated by Django 4.0.3 on 2022-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0002_academicrecognition_year_internship_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='faculty',
            field=models.CharField(max_length=50),
        ),
    ]
