# Generated by Django 4.0.3 on 2022-03-19 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0004_alter_degree_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='description',
        ),
        migrations.CreateModel(
            name='PreviousJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='previous_job', to='spapp.activities')),
            ],
        ),
    ]
