# Generated by Django 4.0.3 on 2022-03-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0005_remove_internship_description_previousjob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
    ]
