# Generated by Django 4.0.3 on 2022-03-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0006_rename_activities_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='end_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='start_date',
            new_name='to_date',
        ),
    ]
