# Generated by Django 4.0.3 on 2022-03-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0007_rename_end_date_activity_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='co_author',
        ),
        migrations.AddField(
            model_name='research',
            name='co_authors',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
