# Generated by Django 3.2.12 on 2022-03-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0009_auto_20220323_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='created_by',
        ),
    ]
