# Generated by Django 3.2.12 on 2022-03-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0010_rename_user_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='studentprofile/theme/static/user_image'),
        ),
    ]
