# Generated by Django 4.0.3 on 2022-03-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
