# Generated by Django 4.0.3 on 2022-03-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0015_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
